### ISSUE TITLE
CtCarrier deprecated on iOS 16

### ISSUE THREAD

**Issue by Maatteogekko** [matszafraniec/device_region#1]
`CTTelephonyNetworkInfo().serviceSubscriberCellularProviders` is deprecated and has no replacement (see [here](https://developer.apple.com/documentation/coretelephony/cttelephonynetworkinfo/3024511-servicesubscribercellularprovide)). 
It is now being stubbed with a value of `'--'` (see [this](https://developer.apple.com/forums/thread/714876?answerId=755389022#755389022)). 

Is there anything that can be done about this?

This is what I am doing as a workaround 
```dart
String? deviceCountryCode = await DeviceRegion.getSIMCountryCode();
if (deviceCountryCode == null) return null;

if (deviceCountryCode == '--') {
  deviceCountryCode = WidgetsBinding.instance.platformDispatcher.locale.countryCode;
}
```

**Comment by matszafraniec** [comment]
Hello @Maatteogekko. Thank you for the update.

I'm little busy these days, I can check this part later this week. Will let you know.

**Comment by matszafraniec** [comment]
@Maatteogekko there is no chance to obtain sim country code from iOS 16.0. I've updated package to return Locale.current.region.[identifier](https://developer.apple.com/documentation/foundation/locale/region/3952434-identifier).
