### ISSUE TITLE
AGP 8 is not supported

### ISSUE THREAD

**Issue by bhumkong** [matszafraniec/device_region#3]
Android Gradle Plugin 8 requires `namespace` property in build.gradle file.

https://developer.android.com/build/releases/past-releases/agp-8-0-0-release-notes#namespace-dsl

**Comment by matszafraniec** [comment]
Thank you. I will take up this, this week.

**Comment by kobeumut** [comment]
Hi @matszafraniec, I create pr about it #4 , can you check it?

**Comment by matszafraniec** [comment]
Thanks @kobeumut. New version (1.1.0) released.
