### ISSUE TITLE
Add basic support for desktop OSes

### ISSUE THREAD

**Issue by mrclauss** [matszafraniec/device_region#7]
Currently under linux and windows there is a missing plugin implementation, resulting in an error when attempting to call getSIMCountryCode.

**Comment by mrclauss** [comment]
I'm currently adding that...

**Comment by matszafraniec** [comment]
In my opinion if package supports only Android and iOS, it should returns error for non-supported platform. What is your opinion @mrclauss ?

**Comment by mrclauss** [comment]
Hi, I fully agree. Now what my PR does is making exactly this behaviour you mentioned consistent for other platforms.
You already wisely defined the error that your package returns from getSIMCountryCode:

"Method returns null in case if for some reason it was not possible to retrieve the information from the SIM slot. "

The pull request introduces the same behaviour for windows and linux, instead of another error that all applications using your plugin need to handle separately (otherwise they need to handle a null return value _and_ a FlutterMissingImplementation exception in parallel).
So while my PR brings no actual feature for windows/linux (yet), it makes life of the users of your plugin easier. 
And it's one first step towards implementing it for desktop platforms ;-)

**Comment by matszafraniec** [comment]
Got it. Agree :) I will accept it and publish changes tomorrow.

Thank you.
